### ISSUE TITLE
BadAttributeIdInvalid

### ISSUE THREAD

**Issue by gabriel-desmarchelier** [KIT-IBPT/epics-open62541#2]
Hello,

Thank you very much for developing this device support. I have been trying to use it and I have a question.

When starting my IOC, connection seems to be established properly, but I encounter the following errors :
```
# Start IOC
#
iocInit
Starting iocInit
############################################################################
## EPICS R3.15.4 $$Date$$
## EPICS Base built Jan 15 2021
############################################################################
2021/11/19 10:36:57.982028 _main_ Open62541Test:bo1 Could not initialize record value: BadAttributeIdInvalid
2021/11/19 10:36:57.987207 _main_ Open62541Test:ao1 Could not initialize record value: BadAttributeIdInvalid
iocRun: All initialization complete
```

and 
```
iocOpcUaOpen62541 > 2021/11/19 10:36:58.992866 cbMedium Open62541Test:bi1 Record processing failed: Error reading from node: BadAttributeIdInvalid
2021/11/19 10:36:58.998029 cbMedium Open62541Test:ai1 Record processing failed: Error reading from node: BadAttributeIdInvalid
```

My EPICS database contains the following :
```
# a pair of bi/bo working on a Boolean data item
record(bi, "$(P)bi1") {
  field(DTYP, "open62541")
  field(INP,  "$(CONN) str:3,\"TestOPC\"\".var3\" Boolean")
  field(SCAN, "1 second")
  field(ZNAM, "False")
  field(ONAM, "True")
}

record(bo, "$(P)bo1") {
  field(DTYP, "open62541")
  field(OUT,  "$(CONN) str:3,\"TestOPC\"\".var3\" Boolean")
  field(ZNAM, "False")
  field(ONAM, "True")
}

# a pair of ai/ao working on a double data item
record(ai, "$(P)ai1") {
  field(DTYP, "open62541")
  field(INP,  "$(CONN) str:3,\"TestOPC\"\".var18\" Float")
  field(SCAN, "1 second")
}

record(ao, "$(P)ao1") {
  field(DTYP, "open62541")
  field(OUT,  "$(CONN) str:3,\"TestOPC\"\".var18\" Float")
}
```

None of these inputs or outputs is working. So I checked with UaExpert which attributes were involved, and it appears that a few have their value to BadAttributeIdInvalid (0x80350000):

![image](https://user-images.githubusercontent.com/65891304/142600877-9192cd0b-0df6-43b1-a138-90f38d057127.png)

So do these attributes have to be defined in order to process the recors properly ? Or is there any way to do differently ?

Thank you for your help

Gabriel

**Comment by smarsching** [comment]
That’s strange, I have never seen this error before. I wonder whether it might be connected to the unusual node IDs with quotation marks in the name…

Which OPC UA server are you using?

**Comment by gabriel-desmarchelier** [comment]
Thank you for your answer.

I am using Siemens S7-1516-3 PN/DP CPU as OPC UA server.

As far as I know, quotation marks are indeed part of the default names when setting OPC UA server through TIA Portal.

I have no choice but to use S7-1500 as OPC UA server, but I will see if I can get rid of quotation marks and try again.

**Comment by smarsching** [comment]
Please let me know how it goes.

I haven’t tested the device support with the S7-1500 series yet, but I also have a project on my list where I am going to have to get this working, so I am very interested in this. At the moment, I have other tasks with higher priorities, so it will be at least a few more weeks until I will find the time to look into this. I will let you know when I find out more.

**Comment by gabriel-desmarchelier** [comment]
The default NodeId set by OPC UA server in Siemens S7-1500 series always includes quotation marks. It is apparently possible to change this, by creating OPC UA specific interface using SiOME (Siemens OPC UA Modeling Editor).
I haven't had a PLC engineer to help me with this yet, so I haven't been able to try and find out if this issue is related to quotation marks or not., but I will tell you if I get the opportunity.

**Comment by eddybl** [comment]
Hey,

so I was able to set up a quick test and it does seem to work for me.
This is the OPC UA Adress:
![image](https://user-images.githubusercontent.com/43214674/152949440-c15b55ea-962d-474e-a9a8-2b59cf614acc.png)

This is my EPICS record:
```
record(ai, "$(P)$(R)1Q1:Current:L1") {
    field(DESC, "1Q1_Strom_L1")
    field(DTYP, "open62541")
    field(SCAN, "I/O Intr")
    field(INP,  "@$(OPC) str:3,\"1Q1_Strom_L1\"")
}
```

If I look at your records there might be a typo?
Your code is:
```
 field(INP,  "$(CONN) str:3,\"TestOPC\"\".var3\" Boolean")
```
but shouldn't it be:
```
 field(INP,  "$(CONN) str:3,\"TestOPC\".\"var3\" Boolean")
```
(position of the dot is different)

**Comment by smarsching** [comment]
@gabriel-desmarchelier As we have not heard back from you, I assume that this issue is resolved. If not, please let us know and we can reopen it.
